### ISSUE TITLE
cannot access test() from live data

### ISSUE THREAD

**Issue by jonneymendoza** [jraska/livedata-testing#29]
I get an error saying that my test class cannot access the TestObserver. 

I have imported your library using     testImplementation 'com.jraska.livedata:testing-ktx:0.6.0' and i am writing my unit tests that is in the Test folder, not the androidTest folder

**Comment by jraska** [comment]
Hello, what do you mean by cannot access TestObserver? It cannot compile or the test crashes?

First please make sure you have also the `'com.jraska.livedata:testing-ktx:0.6.0'` dependency.

Do you use new `androidx` packages or older `support` packages in your app? Version 0.6.0 of liveData-testing supports only the androidx package, because it imports LiveData from there, in case you still have old `support` packages imported in your app, then please use version 0.2.0.

**Comment by jonneymendoza** [comment]
That fixed it. sorry i only included the ktx one! adding both worked! thanks
