### ISSUE TITLE
Consider matching function names/behaviour to RxJava TestObserver

### ISSUE THREAD

**Issue by lordcodes** [jraska/livedata-testing#51]
There are some differences in naming and behaviour between the two libraries, which has confused me a few times when using LiveData testing.

There may be more than I mention below, but the ones that I notice each time:

1. RxJava uses "assertValues", whereas LiveData Testing uses "assertValueHistory".
2. RxJava TestObserver "assertValue" works like "assertValueHistory" with single element. It checks that only one value was received and it matched the argument. LiveData-Testing instead, assertValue just checks the last received value for equality.

Maybe I am wrong in thinking that they should work the same way, as they are different libraries, just wondered what your thoughts on it were.

**Comment by jraska** [comment]
Hi, thanks for raising this. I though about it a lot back then so now I can rethink this. :)

The reason why I did choose different naming is that in my eyes `LiveData` and `Observable` are two different things. 

["`LiveData` is an observable data holder class](https://developer.android.com/topic/libraries/architecture/livedata)", but ["`Observable` is  optionally multi-valued base reactive class."](http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html) - in simple words I see Observable modelling more stream or flow, but `LiveData` is more just an extended version of a value wrapper.
As a value wrapper my thoughts were that the thing, which matters more is the current value, not the previous "emissions". That is why `ref 2.` `assertValue` checks only the current value within `LiveData`
Also `Observable` models for me sequence of values, opposed to that `LiveData` models just one value. That was the reason why `ref 1.` I did choose different naming `assertValueHistory` for such method, because I see it as a history of one value, opposed to sequence in case of `Observable`.

I can imagine this is confusing, but please let me know if that rationale makes sense.

Looking at this it could be renamed as your question confirms it can confuse, but one of the rationales to make ti different was also that many methods from RxJava assertions don't make that much sense for LiveData. SO it was more inspration than copying :)

**Comment by lordcodes** [comment]
That's a very good point, the differences do make it clear that it is a different thing.
