### ISSUE TITLE
Testing LiveData Transformations causes NPE

### ISSUE THREAD

**Issue by iRYO400** [jraska/livedata-testing#55]
Testing ViewModel which uses Transformations live data. 
Tested on both versions 1.1.1 and 1.1.2

ViewModel has:
```
    val counterList: LiveData<List<CounterDto>> =
        Transformations.map(counterRepository.findCounters()) {
            it
        }
```

Test:
```
    @Test
    fun `get counters live data, when result is empty, return empty` () {
        // given
        val expected = MediatorLiveData<List<CounterDto>>().init(emptyList())
        `when`(counterRepository.findCounters()).thenReturn(expected)

        // when
        viewModel.counterList.test() // **Cause NPE**

        // then
        verify(counterRepository, times(1)).findCounters()
    }
```

Stack-trace:
```
java.lang.NullPointerException
	at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
	at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
	at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
	at com.jraska.livedata.TestObserver.test(TestObserver.java:302)
	at com.jraska.livedata.TestObserverKt.test(TestObserver.kt:6)
```

Under debug:
![изображение](https://user-images.githubusercontent.com/12654767/77441439-a206a580-6e13-11ea-839e-b03a4b60f586.png)

![изображение](https://user-images.githubusercontent.com/12654767/77441469-a92db380-6e13-11ea-9f7b-f2328849138c.png)

**Comment by jraska** [comment]
Hi, thanks for using the library :)

All what `TestObserver` does is registering an observer with `observerForever` method. I would be suspicious about the use of Mockito here, because it looks like someone returns a mock and that mock returns null for some cases.

One idea could be looking into who fills the `mSources` map, because that is where the null object comes from.

If there is more insights needed please provide standalone example, but I'm quite strong in belief there is a Mockito in play here.

Thanks and please let me know if there is anything new.

**Comment by iRYO400** [comment]
> I would be suspicious about the use of Mockito here, because it looks like someone returns a mock and that mock returns null for some cases.

Exactly! :)
It happens because I initialize ViewModel in `@Before setUp` before mocking the result of mock repository. After reordering NPE has gone.

But it increases boilerplate, cause I need to move ViewModel init to every test :(

Thanks!

**Comment by jraska** [comment]
Glad to here the problem is gone :)
